from collections.abc import Iterable

from . import (
    SupportsAggregate,
    SupportsAll,
    SupportsAny,
    SupportsAppend,
    SupportsAverage,
    SupportsCast,
    SupportsChunk,
    SupportsConcat,
    SupportsContains,
    SupportsCount,
    SupportsDistinct,
    SupportsExcept,
    SupportsGroupBy,
    SupportsGroupJoin,
    SupportsIntersect,
    SupportsJoin,
    SupportsMax,
    SupportsMin,
    SupportsOrder,
    SupportsPrepend,
    SupportsReverse,
    SupportsSelect,
    SupportsSequenceEqual,
    SupportsSingle,
    SupportsSkip,
    SupportsSum,
    SupportsTake,
    SupportsTypeOf,
    SupportsUnion,
    SupportsWhere,
)


class Enumerable[TSource](
    Iterable[TSource],
    SupportsAggregate[TSource],
    SupportsAll[TSource],
    SupportsAny[TSource],
    SupportsAppend[TSource],
    SupportsAverage[TSource],
    SupportsCast[TSource],
    SupportsChunk[TSource],
    SupportsConcat[TSource],
    SupportsContains[TSource],
    SupportsCount[TSource],
    SupportsDistinct[TSource],
    SupportsExcept[TSource],
    SupportsGroupBy[TSource],
    SupportsGroupJoin[TSource],
    SupportsIntersect[TSource],
    SupportsJoin[TSource],
    SupportsMax[TSource],
    SupportsMin[TSource],
    SupportsOrder[TSource],
    SupportsPrepend[TSource],
    SupportsReverse[TSource],
    SupportsSelect[TSource],
    SupportsSequenceEqual[TSource],
    SupportsSingle[TSource],
    SupportsSkip[TSource],
    SupportsSum[TSource],
    SupportsTake[TSource],
    SupportsTypeOf[TSource],
    SupportsUnion[TSource],
    SupportsWhere[TSource],
): ...
