from . import (
    SupportsAggregation,
    SupportsAppend,
    SupportsAverage,
    SupportsChunk,
    SupportsCollectiveConditionCheck,
    SupportsConcatenation,
    SupportsCount,
    SupportsDistinction,
    SupportsExistenceCheck,
    SupportsGroup,
    SupportsGroupJoin,
    SupportsIndivisualConditionCheck,
    SupportsIntersection,
    SupportsJoin,
    SupportsMaximum,
    SupportsMinimum,
    SupportsSubtraction,
    SupportsTransformation,
    SupportsTypeFilter,
)


class Queryable[TSource](
    SupportsAggregation[TSource],
    SupportsAppend[TSource],
    SupportsAverage[TSource],
    SupportsChunk[TSource],
    SupportsCollectiveConditionCheck[TSource],
    SupportsConcatenation[TSource],
    SupportsCount[TSource],
    SupportsDistinction[TSource],
    SupportsExistenceCheck[TSource],
    SupportsGroup[TSource],
    SupportsGroupJoin[TSource],
    SupportsIndivisualConditionCheck[TSource],
    SupportsIntersection[TSource],
    SupportsJoin[TSource],
    SupportsMaximum[TSource],
    SupportsMinimum[TSource],
    SupportsSubtraction[TSource],
    SupportsTransformation[TSource],
    SupportsTypeFilter[TSource],
): ...
