from collections.abc import Iterable

from . import (
    SupportsAggregation,
    SupportsAppend,
    SupportsAverage,
    SupportsChunk,
    SupportsCollectiveConditionCheck,
    SupportsComparison,
    SupportsConcatenation,
    SupportsCount,
    SupportsDistinction,
    SupportsExistenceCheck,
    SupportsGroup,
    SupportsGroupJoin,
    SupportsIndivisualConditionCheck,
    SupportsIntersection,
    SupportsJoin,
    SupportsMaximum,
    SupportsMinimum,
    SupportsOrder,
    SupportsPrepend,
    SupportsReverse,
    SupportsSelect,
    SupportsSingle,
    SupportsSkip,
    SupportsSubtraction,
    SupportsSum,
    SupportsTake,
    SupportsTransformation,
    SupportsTypeFilter,
    SupportsUnion,
)


class Queryable[TSource](
    Iterable[TSource],
    SupportsAggregation[TSource],
    SupportsAppend[TSource],
    SupportsAverage[TSource],
    SupportsChunk[TSource],
    SupportsCollectiveConditionCheck[TSource],
    SupportsComparison[TSource],
    SupportsConcatenation[TSource],
    SupportsCount[TSource],
    SupportsDistinction[TSource],
    SupportsExistenceCheck[TSource],
    SupportsGroupJoin[TSource],
    SupportsGroup[TSource],
    SupportsIndivisualConditionCheck[TSource],
    SupportsIntersection[TSource],
    SupportsJoin[TSource],
    SupportsMaximum[TSource],
    SupportsMinimum[TSource],
    SupportsOrder[TSource],
    SupportsPrepend[TSource],
    SupportsReverse[TSource],
    SupportsSelect[TSource],
    SupportsSingle[TSource],
    SupportsSkip[TSource],
    SupportsSubtraction[TSource],
    SupportsSum[TSource],
    SupportsTake[TSource],
    SupportsTransformation[TSource],
    SupportsTypeFilter[TSource],
    SupportsUnion[TSource],
): ...
