name: CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync

  lint:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - uses: ./.github/workflows/lint

  typecheck:
    runs-on: ubuntu-latest
    needs: [setup-environment, lint]
    steps:
      - uses: ./.github/workflows/typecheck

  unittest:
    runs-on: ubuntu-latest
    needs: [setup-environment, lint, typecheck]
    steps:
      - uses: ./.github/workflows/unittest
